name: myWorkflow

on: 
  push:
    branches:
      - master
      

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      myVar: ${{ steps.setVar.outputs.varValue }}
    steps:
      - name: Set myVar output
        id: setVar
        run: echo "::set-output name=varValue::myValue"
      - name: Checkout code
        uses: actions/checkout@v2
 
  build2:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - name: Get myVar input
        run: echo ${{ needs.build1.outputs.myVar }}

      - name: Checkout code
        uses: actions/checkout@v2

